// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dloiedvwabxikhbxbziq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsb2llZHZ3YWJ4aWtoYnhiemlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTUxMDEsImV4cCI6MjA2MjEzMTEwMX0.vVK9BAAotr9spvBQ-OQQGS_79XF28-uxD4ofV7RRw6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);